import os

url         = os.environ.get('SUPABASE_URL', '')
key         = os.environ.get('SUPABASE_KEY', '')
service_key = os.environ.get('SUPABASE_SERVICE_KEY', '')

content = f"""/* Auto-generated by Netlify build — do not edit manually */
window.SUPABASE_URL         = '{url}';
window.SUPABASE_KEY         = '{key}';
window.SUPABASE_SERVICE_KEY = '{service_key}';
"""

os.makedirs('js', exist_ok=True)
with open('js/config.js', 'w') as f:
    f.write(content)

print('config.js generated successfully')
